  steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/infra-rhino-386109/docker-piwigo/piwigo:latest', './']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/infra-rhino-386109/docker-piwigo/piwigo:latest']
