from php:7-fpm

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
	libexif-dev \
        ffmpeg \
        mediainfo \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-jpeg\
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install  mysqli \
    && docker-php-ext-install exif

RUN sed -i "s@;php_flag.display_errors. = off@php_flag[display_errors] = off@" /usr/local/etc/php-fpm.d/www.conf 
RUN sed -i "s@;php_admin_value.error_log. @php_admin_value[error_log] @" /usr/local/etc/php-fpm.d/www.conf 
RUN sed -i "s@;php_admin_flag.log_errors. @php_admin_flag[log_errors] @" /usr/local/etc/php-fpm.d/www.conf 
RUN echo 'php_admin_value[date.timezone] = Europe/Paris' >> /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/;php_admin_value.memory_limit. = 32M/php_admin_value[memory_limit] = 256M/' /usr/local/etc/php-fpm.d/www.conf 
RUN echo 'php_admin_value[post_max_size] = 250M' >> /usr/local/etc/php-fpm.d/www.conf
RUN echo 'php_admin_value[upload_max_filesize] = 250M' >> /usr/local/etc/php-fpm.d/www.conf


RUN \
    apt-get update && \
    apt-get install unzip libldap2-dev -y && \
    rm -rf /var/lib/apt/lists/* && \
    docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \
    docker-php-ext-install ldap

# Add src
ADD piwigo-12.1.0.zip /var/www/
ADD Ldap_Login_2.10d.zip /var/www
ADD AdminTools_12.1.0.zip /var/www
ADD rv_tscroller_2.7.a.zip /var/www
ADD GThumb_12.a.zip /var/www
ADD bootstrap_darkroom_2.5.0.zip /var/www
 
RUN cd /var/www/ && unzip /var/www/piwigo-12.1.0.zip && rm -rf html && mv piwigo html && \
    cd /var/www/html/plugins && unzip -o /var/www/Ldap_Login_2.10d.zip && \
    cd /var/www/html/plugins && unzip -o /var/www/AdminTools_12.1.0.zip && \
    cd /var/www/html/plugins && unzip -o /var/www/rv_tscroller_2.7.a.zip && \
    cd /var/www/html/plugins && unzip -o /var/www/GThumb_12.a.zip && \
    cd /var/www/html/themes && unzip -o /var/www/bootstrap_darkroom_2.5.0.zip

ADD database.inc.php /var/www/html/local/config/database.inc.php
ADD jo-mat /var/www/html/template-extension/jo-mat
ADD picture_nav.tpl /var/www/html/themes/bootstrap_darkroom/template/picture_nav.tpl
ADD _photoswipe_js.tpl /var/www/html/themes/bootstrap_darkroom/template/_photoswipe_js.tpl

# RUN chown -R www-data:www-data /var/www/html

ADD t.php /
ADD fpm-entrypoint.sh /fpm-entrypoint.sh

CMD ["/fpm-entrypoint.sh"]
